### ISSUE TITLE
Bundled libraries

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#10]
I submitted a review request for guayadeque fedora package.

The blockers are bundling. Note that this is relevant for 
all kind of packaging, notably Debian/Ubuntu as well as Fedora.

The issue is the bundled library wxcurl in guayadeque.
Is it possible to unbundle wxcurl from guayadeue and create wxcurl as a separately library?

it would be interesting to hear your opinion on 
if/how/when to unbundle wxcurl.

martinkg

**Comment by anonbeat** [comment]
the files that guayadeque uses from wxcurl have some patches I sent to the wxCurl developer long ago. He replied my email saying that it will be included, but never did. This is why I am using this patched files.

**Comment by martinkg** [comment]
problem solved wxcurl was unbundled and replaced by libcurl.
