### ISSUE TITLE
Guayadeque can't open my m3u8 playlist but Winamp, Deadbeef, qmmp, and foobar2000 can

### ISSUE THREAD

**Issue by AlexFolland** [anonbeat/guayadeque#105]
I'm running Manjaro XFCE Mikah 20.1.  I'm running Guayadeque 0.4.6-5d2432ee.

I want to find a media player that has Winamp's intuitive and searchable media library system.  Guayadeque seems to have that, which is awesome and apparently rare in Linux.

So, I tried installing and opening Guayadeque and enqueuing my playlist by dragging it from Nemo, my file manager.  Nothing happened.  I tried again, this time from the built-in "File Browser" in Guayadeque.  Again, nothing happened.  I was expecting the tracks in the playlist to be queued in the Now Playing Playlist, which is the behavior of every other media player I've tried lately.

I tried clicking "Help" -> "Help" in the menu bar with the intention to search about how to load a playlist, but that did nothing.  Not only did no help window appear, but no error prompt or output of any kind appeared.

I tried googling "Guaydeque m3u8" and "Guayadeque load playlist", and that led me to figure out that I should try to use a static playlist from adding my playlists directory as a collection with "Create playlists on scan" enabled.  I did that and enabled "Playlists" view in my new "Playlists" collection, but the list of static playlists was empty.  The folder I'd added contains several m3u and m3u8 playlist files which define relative and absolute audio file paths inside, but all playlists were seemingly ignored.  Absolutely nothing appeared in the list.

Guayadeque gives me no information when trying to load this playlist through any of the methods I tried.  It simply does nothing without an error message prompt, error entry in the Now Playing Playlist, or any other output.

Here's info about the playlist file I wish to load by dragging into the Now Playing Playlist:

* It is in .m3u8 format which is a UTF-8 text file.
* Its first line says `#EXTM3U`.
* Starting with the second line, every other line says `#EXTINF:` followed by some metadata which includes the display name of the track in the playlist.
* Starting with the third line, every other line has the file path relative to the playlist's location in the file system.
* It uses relative file paths with ".." so that the playlist can work when mounted anywhere.
* This is the same exact playlist file I load in all media players to test them, and it contains the list of my favorite music from my audio library.
* It works in foobar2000 in iOS 13.4.1, Winamp in Windows 7, Deadbeef in the exact same Manjaro XFCE installation, and qmmp also in the same Manjaro XFCE installation.  Guayadeque is the first media player that has been unable to load it.

Here's the playlist file itself.  Don't forget to set text encoding in your browser to Unicode to view it properly.

https://lex.clansfx.co.uk/dump/b0023079427be4cb913c69da00cbc48c/clip.txt

**Comment by anonbeat** [comment]
Can you try renaming the m3u8 file to m3u ?

**Comment by AlexFolland** [comment]
That did something!  After dragging the .m3u file to the Now Playing Playlist from Nemo, Guaydeque enqueued many of the files from the playlist.  However, it omitted various miscellaneous files from the list, such as .MOD, .XM, and .SPC files.  I would expect those files to appear in the list, but with an error on each file explaining that it couldn't be loaded instead of being omitted entirely.

Also, after reopening the program after I lost power unexpectedly, the Now Playing Playlist was wiped.  It doesn't seem to be preserving the list when changed.  I would expect the list to be auto-saved like Winamp does with the [Playlist Undo](https://winampplugins.co.uk/plu.html) plugin installed with the "Save the undo queue on all handled changes" option enabled, so that even in the event of a power loss or crash, the Now Playing Playlist is still present at the beginning of the next session.

**Comment by anonbeat** [comment]
.mod, .xm and .spc files are not supported and are ignored. The playlist is saved on close. If the application was closed by a power outage it opened with the previously saved playlist.

Thanks for your comments.

**Comment by AlexFolland** [comment]
Guayadeque is reading only m3u files with the default system encoding which may not be UTF-8 depending on system locale, and not reading m3u8 files, which are similar but always UTF-8.  A workaround of renaming files to the wrong file extension doesn't resolve this issue.

From Wikipedia about the M3U file format:

"An M3U file is a plain text file that specifies the locations of one or more media files. The file is saved with the 'm3u' filename extension if the text is encoded in the local system's default non-Unicode encoding (e.g., a Windows codepage), or with the 'm3u8' extension if the text is UTF-8 encoded."
