### ISSUE TITLE
problem when trying to modify the settings in Mageia 8

### ISSUE THREAD

**Issue by filochard** [anonbeat/guayadeque#112]
Hi
The Mageia team has been able to build Guayadeque with the last wxgtk with your patches...
 thanks a lot for those
Nevertheless I encounter a problem when trying to modify the settings 

Here is the xml file (I have modified the extension from xml to txt to attach it)
[guayadeque.txt](https://github.com/anonbeat/guayadeque/files/5729789/guayadeque.txt)

**Comment by anonbeat** [comment]
Please check with latest changes.

**Comment by filochard** [comment]
Thanks a lot for your quick answer, and for the quick changes in the code
I propose them to the Mageia packagers to test

**Comment by filochard** [comment]
Hi
A Mageia packager added your last commit as a patch but this leads to the same problem when trying to modify the settings.
(Perhaps would it be better to use a git clone than the last tag 0.4.6 with several patches)

here is the xml file (I have modified the extension from xml to txt to attach it)
[guayadeque2.txt](https://github.com/anonbeat/guayadeque/files/5739674/guayadeque2.txt)
Thanks for your job (I think it's one of the best audio reader)

**Comment by anonbeat** [comment]
Please try to do a backtrace as explained here https://www.guayadeque.org/viewtopic.php?f=3&t=468 and be sure you are using lastest version

**Comment by filochard** [comment]
Hi 
Indeed no need for a backtrace : everything is OK ... sorry for the noise in my last comment !
A new package was made on december 24th with a gitclone of the last master from 2020-12-22 and no more problem occurs.

The last packages were made by adding patches to the last tagged 0.4.6 version, and apparently some of your precedent commits had been forgotten, causing the problem we met...
your two last fixes for wxWidgets 3.1.4 have resolved everything

Thanks again for your quick answers and quick commits
