### ISSUE TITLE
bogus strncpy in string_read_callback

### ISSUE THREAD

**Issue by olafhering** [anonbeat/guayadeque#113]
According to the curl documentation, and the actual `curl.h`, [CURLOPT_READFUNCTION](https://curl.se/libcurl/c/CURLOPT_READFUNCTION.html) is supposed to fill an array of bytes. Therefore the usage of `strncpy` is wrong.

I guess the function has to look like this:
````c++
size_t string_read_callback( char * buffer, size_t size, size_t nitems, wxCharBuffer * instring )
{
    size_t Retval;
    size_t BufLen = size * nitems;
    size_t InLen = strlen( * instring );

    Retval = InLen > BufLen ? BufLen : InLen;
    memcpy(  buffer, ( const char * )( * instring ), Retval );

    wxString remaining = wxString( * instring, wxConvLibc ).Right( InLen - Retval );
    * instring = remaining.ToAscii();

    return Retval;
}
````

**Comment by anonbeat** [comment]
If its wrong the use of strncpy then its wrong the use of strlen to set the length of the input string.

**Comment by olafhering** [comment]
The `strlen` is likely ok, if the input is really a `C string`. The terminating NUL byte will not be part of the data stream either way.

**Comment by anonbeat** [comment]
Ok thank you for  pointing it to me... I will change it asap.

**Comment by olafhering** [comment]
Thanks for 3632ef8afe65ccd056acfb092e860e5e1657bc6e.
`buffer` is of type `char *` I think, not `void *`.

**Comment by anonbeat** [comment]
> `buffer` is of type `char *` I think, not `void *`.

The example at https://curl.se/libcurl/c/CURLOPT_READFUNCTION.html its used as void * , but yes looks like its char *

**Comment by olafhering** [comment]
One more thought: Instead of `wxCharBuffer`, some type with a built-in iteration counter should be used. This counter would track how many bytes each invocation of `string_read_callback` has consumed.
