### ISSUE TITLE
guayadeque screenshots of verson 0.4.x

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#13]
Is there currently a homepage of Guayadeque with images of the version 0.4.x.
The reason for my question is, that I want to create a appdata.xml with the links to the actual images.
https://fedoraproject.org/wiki/Packaging:AppData

Thanks Martin

**Comment by anonbeat** [comment]
see here http://guayadeque.org/index.php?p=/page/screenshots
