### ISSUE TITLE
stange crash on Mageia8 32bits

### ISSUE THREAD

**Issue by filochard** [anonbeat/guayadeque#137]
Hi

I have been using Guayadeque for some years on my 64bits computer with Mageia installed
Thanks to you, Guayadeque could be built upon gtk3 wxgtk 3.1.4 and then wxgtk 3.1.5 for Mageia8 and it's OK on my 64bits computer

But I recently found a problem :
I have an old 32 bits laptop with Mageia8 32bits installed (I use it to travel or navigate)
I installed the Guayadeque package and tried to launch it but it aborted by a crash
I asked other Mageia users to test it on 32 bits systems and they got the same crash

NB : Every Mageia packages are built (or updated) at the same time with the same versions for 32bits, 64bits, arm7 and aarch64
The same dependencies with the same version are installed on both my 32bits and 64bits computers

I tried to use different kernels, I tried to rebuild Guayadeque with your last code from december 1st
No way : always crash with the same bug report

I attach the debug report (converted from xml to txt since github doesn't accept xml files) 
you may jump to lines 420 to 440
[guayadeque.txt](https://github.com/anonbeat/guayadeque/files/7684979/guayadeque.txt)

Maybe Guayadeque is no more useable on 32bits systems ?

**Comment by filochard** [comment]
Hi again
I forgot to give the address of the bug report on Mageia Bugzilla , here it is :
https://bugs.mageia.org/show_bug.cgi?id=29742

Regards

**Comment by anonbeat** [comment]
I will try to reproduce the problem here and see what can I do.

**Comment by filochard** [comment]
I think this issue may be closed
It seems to be caused by an error when packaging for Mageia and not by the code of Guayadeque itself
I could buid and install with the simple command line
(I'm gonna dig what is wrong in the spec file of Mageia...)

**Comment by anonbeat** [comment]
Thanks for reporting
