### ISSUE TITLE
appdata.xml file for Gnome Software Center

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#14]
Hi Juan,

could you please add the attached appdata.xml file to guayadeque, so that it can installed with the Gnome Software Center. see: https://people.freedesktop.org/~hughsient/appdata/
Patch see attachement 
[guayadeque-appdata.txt](https://github.com/anonbeat/guayadeque/files/322344/guayadeque-appdata.txt)
guayadeque-appdata.diff

Thanks Martin

**Comment by anonbeat** [comment]
Done. Thank you

**Comment by martinkg** [comment]
please could you submit this smal fix to guayadeque.appdata.xml

```
--- guayadeque.appdata.xml.orig	2016-06-19 19:11:44.775639871 +0200
+++ guayadeque.appdata.xml	2016-06-19 19:12:09.474366839 +0200
@@ -22,5 +22,5 @@
     <screenshot>http://guayadeque.org/uploads/screenshots/Guayadeque.Screenshot_Playlists.png</screenshot>
   </screenshots>
   <url type="homepage">http://guayadeque.org/</url>
-  <updatecontact>Juan Rios <anonbeat@gmail.com></updatecontact>
+  <updatecontact>anonbeat@gmail.com</updatecontact>
 </application>
```

Thanks Martin

**Comment by anonbeat** [comment]
yes. Its up
