### ISSUE TITLE
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):

### ISSUE THREAD

**Issue by Dari0GR** [anonbeat/guayadeque#141]
Alguien podría ayudarme por favor.

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find FFTW (missing: FFTW_LIBRARIES FFTW_INCLUDE_DIRS)
CMake Warning at CMakeLists.txt:95 (message):
  FFTW library not available.  Some targets will not be built

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dariogr/Desktop/kbd-audio/build

**Comment by anonbeat** [comment]
FFTW is not a guayadeque dependency.
