### ISSUE TITLE
release version under Help - About

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#15]
Hi,

Help - about shows only the main release 0.4.1, not 0.4.1-b032d17
https://martinkg.fedorapeople.org/ErrorReports/guayadeque/Help_about.png

this are my build options:
http://pkgs.fedoraproject.org/cgit/rpms/guayadeque.git/tree/guayadeque.spec

**Comment by anonbeat** [comment]
With commit 9f03692 should work...

**Comment by martinkg** [comment]
is it possible to show the version and git release in one line ?
https://martinkg.fedorapeople.org/ErrorReports/guayadeque/Help_about1.png

**Comment by anonbeat** [comment]
It is showing in one line here... Will try to see where the problem comes from...

**Comment by anonbeat** [comment]
I checked and everything looks fine... Dunno what can be... Will continue taking a look... I set a huge font size and even with that it looks fine...

![splash screen screenshot_2016-06-21_22-03-36](https://cloud.githubusercontent.com/assets/724089/16246218/32c89364-37fc-11e6-99ea-88032603b00a.png)

**Comment by martinkg** [comment]
ok, tested only on vmware and i played a little bit with the settings, now it's displayed in one line.

**Comment by anonbeat** [comment]
ok nice. Thank you
