### ISSUE TITLE
error: ambiguous overload for 'operator!=' (operand types are 'wxCStrData' and 'long int')

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#155]
Hi,

when i compile guayadeque-0.4.7 on Fedora rawhide and f38 (gcc13) i get the following error messages:

/builddir/build/BUILD/guayadeque-0.4.7/src/taginfo/TagInfo.cpp: In member function
'virtual bool Guayadeque::guGStreamerTagInfo::ReadGStreamerTags(const
wxString&)':
/usr/include/glib-2.0/glib/gstrfuncs.h:209:22: error: ambiguous overload for
'operator!=' (operand types are 'wxCStrData' and 'long int')
  209 |     (G_LIKELY ((STR) != NULL) ?                                               \
      |                      ^

the error could be solved by the following patch:

```
--- src/taginfo/TagInfo.cpp.orig	2023-02-24 13:14:52.785519249 +0100
+++ src/taginfo/TagInfo.cpp	2023-02-24 13:15:54.179180143 +0100
@@ -2530,7 +2530,7 @@
     gchar *uri;
     if( gst_uri_is_valid ( filename.c_str() ) )
     {
-        uri = g_strdup( filename.c_str() );
+        uri = g_strdup ( (const gchar*)filename.c_str() );
     }
     else
     {
```

Regards
Martin

**Comment by anonbeat** [comment]
Thank you
