### ISSUE TITLE
Migrate from obsolete libindicate to ayatana appindicators implementation

### ISSUE THREAD

**Issue by pacho2** [anonbeat/guayadeque#156]
libayatana-appindicator and libayatana-indicator are the only appindicators implementation that are still maintained and developped, while libappindicator/libindicate are unmaintained for ages.

OpenSUSE already migrated and Debian is ongoing. 
https://wiki.debian.org/Ayatana/IndicatorsTransition

Most reverse deps already migrated or try to use ayatana and fallback to old impl if not found but guayadeque is one of the last consumers :/

Thanks a lot for your help

**Comment by anonbeat** [comment]
Removed libindicate support.
