### ISSUE TITLE
No package 'gstreamer-tag-1.0' found on fedora platform

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#16]
Hi Juan,

when compiling the recent git version on fedora i get the error message: No package 'gstreamer-tag-1.0' found

fc24 log file from the fedora build server:
https://kojipkgs.fedoraproject.org//work/tasks/5502/14755502/build.log

fc25 log file from the fedora build server:
https://kojipkgs.fedoraproject.org//work/tasks/5519/14755519/build.log

on fedora there are only this gstreamer components available:

`# rpm -qa |grep gstreamer |sort
gstreamer-0.10.36-14.fc24.x86_64
gstreamer1-1.8.2-1.fc24.x86_64
gstreamer1-debuginfo-1.8.1-1.fc24.x86_64
gstreamer1-devel-1.8.2-1.fc24.x86_64
gstreamer1-libav-1.8.2-1.fc24.x86_64
gstreamer1-plugins-bad-free-1.8.2-1.fc24.x86_64
gstreamer1-plugins-bad-free-extras-1.8.2-1.fc24.x86_64
gstreamer1-plugins-bad-freeworld-1.8.2-1.fc24.x86_64
gstreamer1-plugins-bad-freeworld-debuginfo-1.4.5-2.fc22.x86_64
gstreamer1-plugins-base-1.8.2-1.fc24.x86_64
gstreamer1-plugins-base-debuginfo-1.8.1-1.fc24.x86_64
gstreamer1-plugins-base-devel-1.8.2-1.fc24.x86_64
gstreamer1-plugins-base-tools-1.8.2-1.fc24.x86_64
gstreamer1-plugins-good-1.8.2-1.fc24.x86_64
gstreamer1-plugins-good-debuginfo-1.8.1-1.fc24.x86_64
gstreamer1-plugins-good-extras-1.8.2-1.fc24.x86_64
gstreamer1-vaapi-1.8.2-1.fc24.x86_64
gstreamer-debuginfo-0.10.36-14.fc24.x86_64
gstreamer-devel-0.10.36-14.fc24.x86_64
gstreamer-ffmpeg-0.10.13-15.fc24.x86_64
gstreamer-plugin-crystalhd-3.10.0-12.fc24.x86_64
gstreamer-plugins-bad-0.10.23-7.fc24.x86_64
gstreamer-plugins-bad-free-0.10.23-32.fc24.x86_64
gstreamer-plugins-bad-nonfree-0.10.23-3.fc24.x86_64
gstreamer-plugins-base-0.10.36-14.fc24.x86_64
gstreamer-plugins-base-debuginfo-0.10.36-14.fc24.x86_64
gstreamer-plugins-base-devel-0.10.36-14.fc24.x86_64
gstreamer-plugins-espeak-0.4.0-9.fc24.x86_64
gstreamer-plugins-fc-0.2-12.fc24.x86_64
gstreamer-plugins-good-0.10.31-16.fc24.x86_64
gstreamer-plugins-good-debuginfo-0.10.31-16.fc24.x86_64
gstreamer-plugins-good-extras-0.10.31-16.fc24.x86_64
gstreamer-python-0.10.22-10.fc24.x86_64
gstreamer-tools-0.10.36-14.fc24.x86_64`

hope you can help.

Regards Martin

**Comment by anonbeat** [comment]
It is included in libgstreamer-plugins-base1.0-dev in ubuntu. Look for something similar in fedora.

Thanks

**Comment by martinkg** [comment]
attached is the list of gstreamer1-plugins-base-devel.txt
[gstreamer1-plugins-base-devel.txt](https://github.com/anonbeat/guayadeque/files/345709/gstreamer1-plugins-base-devel.txt)

**Comment by anonbeat** [comment]
see this ?
/usr/lib64/pkgconfig/gstreamer-tag-1.0.pc

This is what I am using now... so this is the package...

**Comment by martinkg** [comment]
ah, thanks for the clarifying words, I will change the BuildRequires from gstreamer1-devel
to gstreamer1-plugins-base-devel
Regards

**Comment by anonbeat** [comment]
Isn't better keep both?

**Comment by martinkg** [comment]
not necassary, because gstreamer1-plugins-base-devel depends on gstreamer1-devel
