### ISSUE TITLE
program exit, when selecting Album Browser

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#19]
crash report attached.
[guayadeque.xml.txt](https://github.com/anonbeat/guayadeque/files/563607/guayadeque.xml.txt)

screenshot:
https://martinkg.fedorapeople.org/ErrorReports/guayadeque/guayadeque-crash-album-browser.png

**Comment by anonbeat** [comment]
This should be fixed with last commit... please check it and let me know...

Thanks for your help

**Comment by martinkg** [comment]
many thanks, issue now fixed.
