### ISSUE TITLE
Edit user radio: box too small to see/edit

### ISSUE THREAD

**Issue by spsf64** [anonbeat/guayadeque#20]
When I try to edit any user radio the "link" option is too small and cannot be resized.
Screenshot attached.
I am running in archlinux, git version r2032

![screenshot_2016-11-01_11-12-19](https://cloud.githubusercontent.com/assets/1877391/19890907/a4493918-a024-11e6-9fb0-8ae31547207a.png)

**Comment by anonbeat** [comment]
That is something to do more with the theme than with anything else... I will make the box resizeable

**Comment by spsf64** [comment]
@anonbeat Wow, thanks for this fast reply, it is working and there is no need to resize!
I think you can move out of beta to stable! Thanks for this great project.

![screenshot from 2016-11-01 17-52-49](https://cloud.githubusercontent.com/assets/1877391/19905059/4fb7439e-a05c-11e6-81ed-e1537a827abf.png)
