### ISSUE TITLE
preferences playback, ugly text display

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#21]
ugly text display in: Random / Smart play modes
https://martinkg.fedorapeople.org/ErrorReports/guayadeque/guayaque-preferences-ugly-text.png

**Comment by spsf64** [comment]
I don't have this problem, maybe it is your theme? Archlinux+arc dark theme.

![screenshot_2016-11-18_09-04-49](https://cloud.githubusercontent.com/assets/1877391/20428079/63542042-ad6e-11e6-80e9-b48cc3fe7392.png)

**Comment by martinkg** [comment]
no success with arc-dark theme on Fedora 25
![guayaque-arc-dark-theme](https://cloud.githubusercontent.com/assets/2564124/20429105/dd7a6d5e-ad8c-11e6-8ac3-2f8e76c89e3f.png)

**Comment by spsf64** [comment]
I notice the problem is not with text, but misplaced - and + signals where in my screenshot you can see up and down arrows.
What DE are you using? Mine is xfce.

**Comment by martinkg** [comment]
Fedora's default desktop environment is GNOME 3, i switched for testing porpuse to xfce, but the same issue.

**Comment by anonbeat** [comment]
I think it is a compatibility problem between theme and wxWidgets. Here looks like @spsf64 screenshot

I wonder why the problem does not appear in the silence detector entry.

**Comment by anonbeat** [comment]
@martinkg : What is the theme used in fedora?

**Comment by martinkg** [comment]
i use arc-dark-theme
![arc-dark-theme](https://cloud.githubusercontent.com/assets/2564124/20474931/54a29314-afc9-11e6-8c9c-ee43a5970c17.png)

**Comment by anonbeat** [comment]
The last commit should fix this issue... please try it and let me know.

Thanks for your help

**Comment by martinkg** [comment]
looks perfect now, great work.

**Comment by martinkg** [comment]
looks perfect now, great work.
