### ISSUE TITLE
Showing music player freezes some parts of the interface

### ISSUE THREAD

**Issue by usernameofchris** [anonbeat/guayadeque#22]
The issue happens when I try to access my music player with Guayadeque. The music player is a Sansa Fuze+ running Rockbox, if that matters. I go to Sources -> SANSA FUZEP -> Show, and then the interface glitches up a bit. The search bar and all playback buttons seem like they're still functional, but they don't change visually when you use them like they're supposed to. Strangely enough, I can still change the size of different parts of the interface. I've attached screenshots of before and after showing the music player so you know what I'm talking about.

First, the normal interface:
![normal](https://cloud.githubusercontent.com/assets/23566004/20452607/f1b3262c-addb-11e6-8235-20c310992452.png)

Then, the glitchy interface after I click on Show:
![glitchy interface](https://cloud.githubusercontent.com/assets/23566004/20452608/f3be47a8-addb-11e6-80a7-41904e601a4a.png)

**Comment by anonbeat** [comment]
Can you run guayadeque from console and send me the output when this happens please ?

**Comment by usernameofchris** [comment]
Sure, here's everything after I start the program up to showing the device:
09:35:18 AM: Initialized locale ( en_US )
09:35:18 AM: Mount Added...
09:35:18 AM: Mount Path: /media/christopher/SANSA FUZEP/
09:35:18 AM: IconStr: '. GThemedIcon drive-removable-media-usb drive-removable-media drive-removable drive'
09:35:18 AM: MediaViewer 'My Music' => '50C8E853'
09:35:19 AM: Library Db Version 21
09:35:19 AM: SetViewMode -1 => 0

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
09:36:31 AM: guLibPanel::IniPanelData( 13101 )
09:36:31 AM: guLibPanel::DoTextSearch( '' )

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
09:36:32 AM: Mount: 'SANSA FUZEP' => '/media/christopher/SANSA FUZEP/'

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
09:36:33 AM: OnCollectionCommand 13100  0 0  1

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
09:36:33 AM: Mount: 'SANSA FUZEP' => '/media/christopher/SANSA FUZEP/'

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
09:36:33 AM: guMainFrame::OnMountMonitorUpdated
09:36:33 AM: Mount: 'SANSA FUZEP' => '/media/christopher/SANSA FUZEP/'
09:36:37 AM: OnCollectionCommand 13114  0 14  0
09:36:37 AM: Doing Library Update in /home/christopher/Music
09:36:37 AM: Updating the podcasts...
09:36:37 AM: MainFrame.Size( 1232, 633 ) -1
09:36:37 AM: MainFrame.Size( 1232, 661 ) -1
09:36:37 AM: Loading 0 -1 => 0 '/home/christopher/Music/Paul McCartney/Pipes of Peace/12. Paul McCartney - Twice in a Lifetime.ogg'
09:36:37 AM: Loading '/home/christopher/Music/Paul McCartney/Pipes of Peace/12. Paul McCartney - Twice in a Lifetime.ogg'
09:36:37 AM: playlist active 0
09:36:57 AM: OnCollectionCommand 13163  3 0  1
09:36:57 AM: MediaViewer Not Found for '5454B62C'
09:36:57 AM: MediaViewer 'SANSA FUZEP' => '5454B62C'
09:36:57 AM: Using config path '/media/christopher/SANSA FUZEP/.is_audio_player'
09:36:58 AM: Library Db Version 21
09:36:58 AM: SetViewMode -1 => 0

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
09:37:09 AM: guLibPanel::IniPanelData( 13164 )
09:37:09 AM: guLibPanel::DoTextSearch( '' )

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(guayadeque:2763): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed

(guayadeque:2763): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
09:37:09 AM: Mount: 'SANSA FUZEP' => '/media/christopher/SANSA FUZEP/'
09:37:09 AM: OnCollectionCommand 13177  3 14  0
09:37:09 AM: Doing Library Update in /media/christopher/SANSA FUZEP/Music/

**Comment by anonbeat** [comment]
Lets try something... close guayadeque and rename the .guayadeque folder to .guayadeque_saved and open the application again...
You will need to reconfigure it from scratch but I hope you will not get this problem... 
Let me know how what happens.

**Comment by usernameofchris** [comment]
Still getting problems with the interface after doing that.
![screenshot from 2016-11-22 18-32-41](https://cloud.githubusercontent.com/assets/23566004/20546334/6f139ed6-b0e2-11e6-89fc-de3ab2c2ce9a.png)

**Comment by anonbeat** [comment]
What is your os, window manager, amd64 or i386, etc ?

**Comment by usernameofchris** [comment]
Ubuntu 16.04 LTS, Unity, amd64.

**Comment by usernameofchris** [comment]
I just checked and the problems persists in Gnome.

**Comment by anonbeat** [comment]
I cant reproduce the problem... Will try to install a ubuntu with unity to check but while I cant reproduce it it is hard to find out what produce it and how to fix it...

**Comment by anonbeat** [comment]
This have been fixed recently.
