### ISSUE TITLE
dependency issues on Archlinux

### ISSUE THREAD

**Issue by oberon2007** [anonbeat/guayadeque#23]
On Archlinux we are currently at **libindicate-12.10** and **wxsqlite3-3.4.1**.
Module checks fail therefor and I'm unable to build the package.
Anything can be done about that?

**Comment by Strubbl** [comment]
aur package guayadeque-git builds successfully with workarounds for that problem

**Comment by oberon2007** [comment]
yes, thanks! I found the [wxsqlite patch](https://aur.archlinux.org/cgit/aur.git/plain/0001-use-cmake-lib-search-procedure-for-wxsqlite3-from-mu.patch?h=guayadeque-git) there.
indicate seems to be just ignored - not sure if that will cause problems later ... in any case it's building now :+1:
