### ISSUE TITLE
Searchfield in 'my music' overlapping 'library view' menu

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#24]
![guayadeque-overlapping-menue](https://cloud.githubusercontent.com/assets/2564124/20635177/dffc732e-b359-11e6-9421-cabcdc94779a.png)

**Comment by anonbeat** [comment]
Will take a look 

Thanks

**Comment by anonbeat** [comment]
changed wxSearchCtrl with wxTextCtrl and it looked fine so the problem comes from wxSearchCtrl.

**Comment by anonbeat** [comment]
Can you please confirm that this is still happening ? I checked with ubuntu 17.10 and its working fine

**Comment by martinkg** [comment]
looks now fine.
thanks for your fix.

**Comment by anonbeat** [comment]
As I told you it was a problem of the wxSearchCtrl component. I did nothing. 
Thank you for your help
