### ISSUE TITLE
guayadeque version in the source code differs from the version on the homepage

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#29]
The version in the source code differs from the version on the homepage

SOURCES:
src/Version.h.in:#define ID_GUAYADEQUE_VERSION  "0.4.5"

HOMEPAGE on https://github.com/anonbeat/guayadeque
Guayadeque Music Player 0.4.1 Beta

**Comment by anonbeat** [comment]
Done 

thanks

**Comment by martinkg** [comment]
thanks for the correction
