### ISSUE TITLE
installation problem with language files on Fedora 25

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#30]
with the old version the language path looks like this:
/usr/share/locale/de/LC_MESSAGES/guayadeque.mo

with the new version the language path includes a second de in the path:
/usr/share/locale/de/LC_MESSAGES/deguayadeque.mo
                           ^                              ^

i don't know if this is a distribution-dependent problem ?
rpm spec file: [guayadeque.spec](https://martinkg.fedorapeople.org/Review/test/guayadeque/guayadeque.spec)

old:

make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/guayadeque-5def972dca0ebdc7997dac6e7dffe1149472ba9b'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/applications/guayadeque.desktop
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/pixmaps/guayadeque.png
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/guayadeque/guayadeque.default.conf
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/guayadeque/equalizers.default.conf
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/guayadeque/lyrics_sources.xml
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/appdata/guayadeque.appdata.xml
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/bin/guayadeque
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/es/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/uk/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/it/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/de/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/fr/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/is/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/nb/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/th/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/cs/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/ru/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/hu/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/sv/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/nl/LC_MESSAGES/guayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.1.beta1git5def972.fc25.x86_64/usr/share/locale/pt_BR/LC_MESSAGES/guayadeque.mo

new:

make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/guayadeque-400f5383ddd175c6408347cc9569da0f3956a1cb'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/applications/guayadeque.desktop
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/pixmaps/guayadeque.png
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/appdata/guayadeque.appdata.xml
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/guayadeque/guayadeque.default.conf
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/guayadeque/equalizers.default.conf
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/guayadeque/lyrics_sources.xml
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/bin/guayadeque
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/es/LC_MESSAGES/esguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/uk/LC_MESSAGES/ukguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/it/LC_MESSAGES/itguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/de/LC_MESSAGES/deguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/fr/LC_MESSAGES/frguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/is/LC_MESSAGES/isguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/nb/LC_MESSAGES/nbguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/th/LC_MESSAGES/thguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/cs/LC_MESSAGES/csguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/ru/LC_MESSAGES/ruguayadeque.mo-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/de/LC_MESSAGES/deguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/fr/LC_MESSAGES/frguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/is/LC_MESSAGES/isguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/nb/LC_MESSAGES/nbguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/th/LC_MESSAGES/thguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/cs/LC_MESSAGES/csguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/ru/LC_MESSAGES/ruguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/hu/LC_MESSAGES/huguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/sv/LC_MESSAGES/svguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/nl/LC_MESSAGES/nlguayadeque.mo
-- Installing: /home/martin/rpmbuild/BUILDROOT/guayadeque-0.4.5-0.2.beta1git400f538.fc25.x86_64/usr/share/locale/pt_BR/LC_MESSAGES/pt_BRguayadeque.mo

**Comment by anonbeat** [comment]
This should be fixed with latest commit...

**Comment by martinkg** [comment]
Thanks, sorks as expected.
