### ISSUE TITLE
Cant sign in for discussions!

### ISSUE THREAD

**Issue by aurabindo** [anonbeat/guayadeque#31]
Google sign-in is failing with a big **Bonk**, and I just cant seem to convince the captcha that I am a human while registering!

Are there any means of quick communication with Guayadeque community, like IRC/Matrix/XMPP ?

**Comment by anonbeat** [comment]
The captcha answer is 'deque' ...

**Comment by anonbeat** [comment]
you can always email me to anonbeat gmail com
