### ISSUE TITLE
increase/decrease volume doesn't work with Ctrl+Up and Ctrl+Down.

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#34]
increase/decrease volume doesn't work with Ctrl+Up and Ctrl+Down.

works only via menu, Controls - Volume Up / Volume Down

**Comment by anonbeat** [comment]
Yes on some controls (mainly scrollwindow based ones) Up and Down are handled even with ctrl modifier... Need to set a new shortcut
