### ISSUE TITLE
In a smartlist, cannot filter by existance of a label

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [anonbeat/guayadeque#38]
I have many songs with labels A and B.

I cannot find songs that contain label A or label B.
I even cannot find something as simple as songs that contain label A.
Only 1 song is found when I have hundreds.  I haven't limited the number of results.

**Comment by anonbeat** [comment]
Just tried and it worked for me... 
![smartplaylist creationg with labels](https://cloud.githubusercontent.com/assets/724089/26753216/6a5c2f84-4859-11e7-9555-9357e54972cc.png)
