### ISSUE TITLE
Request: Add global keyboard shortcuts

### ISSUE THREAD

**Issue by geo909** [anonbeat/guayadeque#39]
Hi, and thanks a lot for guaydeque.

It would be great if there were global keyboard shortcuts. Is there any plans to implement this?

**Comment by anonbeat** [comment]
Guayadeque should support multimedia keys. 

What other shourcuts do you want to support globaly?

**Comment by robbat2** [comment]
@geo909 I gave up on supporting it directly in media keys everywhere, because it causes problems with capturing keys in some cases, and instead set up xbindkeys to trigger dbus events.

**Comment by geo909** [comment]
Ok, thanks a lot for the heads up.
