### ISSUE TITLE
Another program instance is already running, aborting

### ISSUE THREAD

**Issue by Lyle-Tafoya** [anonbeat/guayadeque#41]
On my freshly rebooted computer I try to run Guayadeque and receive the following error:

(17:34:49: Error showing window
17:34:49: Another program instance is already running, aborting.

Guayadeque is not already running (i confirmed via the task manager). My computer is running Arch Linux. This was working before. In order to resolve this issue I had to dive into the source code to determine that the ~/.guayadeque/.guayadeque-username file had to be removed. This fixes the issue, but I am unsure of how this happened or whether there is any way for non-technical users to resolve this issue. Perhaps instead of displaying an error to stdout and then closing, it might make more sense to have a proper dialog box which explains the issue and gives an option to automatiically resolve it if the user is sure that guayadeque isn't already running.

**Comment by anonbeat** [comment]
This have been implemented in latest commit. Thank you for your suggestion.
