### ISSUE TITLE
Editing a tag with quodlibet/ex falso takes no effect in Guayadeque's library

### ISSUE THREAD

**Issue by Tinymeat** [anonbeat/guayadeque#43]
In order to have my music library correctly tagged I used "Ex falso" to include the "albumartist" tag in several music files. When opening Guayadeque's tag editor I recognized that these tag fields are all empty.
What is the reason for this behaviour or is it simply a PEBKAC?

**Comment by anonbeat** [comment]
Can you please send me one or two files with this behavior please ?

**Comment by anonbeat** [comment]
Thank you for yout email providing the sample files. With that files I could confirm that the problem is that this programs are using ID3 v2.4.0 where Guayadeque which uses Taglib supports ID3 v2.3.0

Thanks for your help
