### ISSUE TITLE
Song is the wrong length; edit song command fails

### ISSUE THREAD

**Issue by PhoenixWizard-Beta** [anonbeat/guayadeque#44]
One song cuts off randomly while playing, and every time I try to edit the song with the ctrl-E option, nothing happens. When I drag the file and it brings up the Import Files window, it says the song is 1 minute 59 seconds long and 10.34 MB in size, when the song is 5 minutes and 13 seconds long and 27 MB in size.

**Comment by anonbeat** [comment]
can you email me the track so I can find where the problem is please ? email it to anonbeat @ gmail . com

**Comment by Strubbl** [comment]
The char `` is causing the problem. I sent you a mail with the conflicting file.

Other chars like `` or `` do not cause a problem.

**Comment by anonbeat** [comment]
Everything is fine here... the problem must come from the codec on your side... 

Sorry I cant help you more...

![screenshot_2017-06-10_20-18-40](https://user-images.githubusercontent.com/724089/27005625-1a0bb678-4e1a-11e7-8cbb-619b4d9f285a.png)
