### ISSUE TITLE
Stop button & backgroud buttons' color fixes are not present in Guayadeque 0.4.5-1

### ISSUE THREAD

**Issue by geplus** [anonbeat/guayadeque#45]
Hi,

**referring to #25 and #26**

none of these changes are present in **guayadeque 0.4.5.1** , despite you wrote me that these features were added.
I use the version present in [Manjaro Linux](https://manjaro.org/) 's repos, updated at the moment I'm writing.

Is this a bug, a miss or another sort of error/problem?

**Comment by anonbeat** [comment]
maybe this is a manjaros packager? its present in the version I build

**Comment by oberon2007** [comment]
Well Manjaro uses the latest release **v0.4.5**, not the latest git version. It is standard for a distro to take the latest release as the official version. This version has been released 5 months ago... Maybe it would be time for a new tag? 😉
