### ISSUE TITLE
unable to run: Gtk-Error

### ISSUE THREAD

**Issue by plgruener** [anonbeat/guayadeque#48]
Caused – maybe – by an update to Arch Linux' Gtk/wx libraries, I cannot longer run Guayadeque. I tried both 'guayadeque-git' in AUR and building straight from source, with following Errors:
```
./src/common/object.cpp(251):` assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxCommandEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
```
with over a hundred similar messages and 
```
(guayadeque:4366): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
fish: “./guayadeque” terminated by signal SIGTRAP
```

Versions of my libraries:
```
gtk2 2.24.31-1
gtk3 3.22.15-1
wxgtk-common 3.0.3.1-6
wxgtk2 3.0.3.1-6
wxgtk3 3.0.3.1-6
wxsqlite3 3.5.5-1
```
If you need any more info, just let me know.

**Comment by Strubbl** [comment]
same here:

```
$ guayadeque 
guayadeque: error while loading shared libraries: libwxcode_gtk2u_wxsqlite3-3.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by Strubbl** [comment]
@plgruener a temporary hack to get the AUR package guayadeque-git working is to add the line to use gtk3:

```
$ git diff PKGBUILD
diff --git a/PKGBUILD b/PKGBUILD
index a49b3db..646ea04 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,7 +3,7 @@
 
 pkgname=guayadeque-git
 _pkgname=guayadeque
-pkgver=0.4.5.r2050.9fec4f7b
+pkgver=0.4.5.r2063.35eaa957
 pkgrel=1
 pkgdesc='Lightweight music player'
 arch=('i686' 'x86_64')
@@ -33,7 +33,8 @@ build() {
   cmake . \
     -DCMAKE_CXX_STANDARD='11' \
     -DCMAKE_BUILD_TYPE='Release' \
-    -DCMAKE_INSTALL_PREFIX='/usr'
+    -DCMAKE_INSTALL_PREFIX='/usr' \
+    -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-gtk3
   make
 }
```

I do not know if there is a better way than hard-coding the path to wx-config-gtk3 into the PKGBUILD. I need to ask people and research. Do you know a better way than this hack?

**Comment by anonbeat** [comment]
sorry but I don't know about Arch packaging

**Comment by philmmanjaro** [comment]
@Strubbl: this is the way to go on arch-based systems. However, it seems **guayadeque** is designed for **wxgtk2** and therefore you have some graphical issues now:

![9c54304a7c56f38262917f92895e7643f937eefc](https://user-images.githubusercontent.com/5050022/27515280-e534d59c-599f-11e7-886f-b7268a87b829.png)

**Comment by Strubbl** [comment]
@philmmanjaro yes, i can reproduce this graphical issue :(

@anonbeat do you have any plans to move to wxgtk3?

**Comment by MarcinWieczorek** [comment]
I can confirm: http://sprunge.us/UBDC
I am the maintainer of the package in the Arch User Repository, please ask if I can help in any way.

**Comment by anonbeat** [comment]
With latest commit maybe the gfx issue are fixed ? can anyone confirm ? on my system doesn't happen so I can't confirm it

**Comment by Strubbl** [comment]
I just tested latest commit. Compiling issue is fixed. Installation works fine, too. But i get errors at startup:

https://gist.github.com/Strubbl/46f0edc5a29498a80ff203d570265f1e

**Comment by MarcinWieczorek** [comment]
Same here.

**Comment by mmetak** [comment]
I build my package with these extra lines:
```
    -DwxWidgets_wxrc_EXECUTABLE='/usr/bin/wxrc-3.0' \
    -DwxWidgets_CONFIG_EXECUTABLE='/usr/bin/wx-config-gtk3' \
    -DwxWidgets_INCLUDE_DIRS='/usr/include/wx-3.0/'
```
No errors, and no graphical issues. (guayadeque-git 20171012.f4cd389f)

![screenshot_20171018_153237](https://user-images.githubusercontent.com/6218030/31721576-028b3288-b41a-11e7-93d2-4a2abfca4c6c.png)

**Comment by Lyle-Tafoya** [comment]
I built it with wxgtk2 and a slightly older version of wxsqlite3 (version 3.4.1-2) and got it working that way without having to change anything from the guayadeque package itself.

**Comment by FSMaxB** [comment]
@mmetak I can confirm this works.
@MarcinWieczorek Maybe this can be used as a workaround for now in the AUR package.

**Comment by Lyle-Tafoya** [comment]
Would it make more sense to build it with a patch to add support for gtk3 (which I believe has not been extensively tested) or does it make more sense to install a gtk2 version of wxsqlite3 so it can be built without any patches?

**Comment by Strubbl** [comment]
Thanks @mmetak 
i adopted your suggestions for the cmake build process: https://aur.archlinux.org/cgit/aur.git/commit/?h=guayadeque-git&id=8b068bedc288ea00dd39f1cbf10b4669712d1495 and https://github.com/Strubbl/aur-guayadeque-git/commit/8b068bedc288ea00dd39f1cbf10b4669712d1495
Now aur package https://aur.archlinux.org/packages/guayadeque-git/ should work again.

I suggest that this issue is resolved and can be closed. Thanks @anonbeat for giving us the possibility to join forces here in this issue.

**Comment by anonbeat** [comment]
Thanks you all you for your support
