### ISSUE TITLE
Variable block size FLAC files cannot be decoded properly

### ISSUE THREAD

**Issue by CartoonFan** [anonbeat/guayadeque#50]
Variable block-sized FLAC files play the first sample and then go mostly silent, with the occasional sample playing in-between. Files encoded with both of the flake encoder's variable block-size options fail to play and exhibit the same behavior.

Also, it's probably part of another bug, but am I correct in assuming that the ReplayGain reference level is hardcoded to 89 DB? Because Guayadeque seems to ignore the value in the tag for the reference level.

Anyway, other than these things, I really like this player!

**Comment by anonbeat** [comment]
can you send me one track that fails to play please ? anonbeat @ gmail . com 

Thanks

**Comment by CartoonFan** [comment]
I sent you a track. Did you receive it?

**Comment by anonbeat** [comment]
Sorry for the late response. I was on hollidays... Yes I received it

thanks

**Comment by anonbeat** [comment]
Tried with gstreamer directly and it must be a problem with the file. Im not sure but if gstreamer cant play it guayadeque cant do more as its based on gstreamer
`jrios@jrosrv:~/Downloads$ gst-launch-1.0 --gst-debug-level=3 filesrc location=Where\ You\ Belong.flac ! decodebin ! audioconvert ! audioresample ! pulsesink
Setting pipeline to PAUSED ...
0:00:00.034105823 16808      0x155c2f0 WARN                 basesrc gstbasesrc.c:3489:gst_base_src_start_complete:<filesrc0> pad not activated yet
Pipeline is PREROLLING ...
0:00:00.039350183 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:896:gst_flac_parse_handle_streaminfo:<flacparse0> Invalid minimum block size: 0
0:00:00.040705286 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:605:gst_flac_parse_frame_header_is_valid:<flacparse0> Block size is not constant
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstPulseSinkClock
0:00:00.162703430 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:605:gst_flac_parse_frame_header_is_valid:<flacparse0> Block size is not constant
0:00:00.162737085 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:605:gst_flac_parse_frame_header_is_valid:<flacparse0> Block size is not constant
0:00:00.163045737 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:605:gst_flac_parse_frame_header_is_valid:<flacparse0> Block size is not constant
0:00:00.163065108 16808 0x7f305c04ea80 WARN               flacparse gstflacparse.c:605:gst_flac_parse_frame_header_is_valid:<flacparse0> Block size is not constant
0:00:00.163356943 16808 0x7f305c04ea80 WARN           audiobasesink gstaudiobasesink.c:1807:gst_audio_base_sink_get_alignment:<pulsesink0> Unexpected discontinuity in audio timestamps of +0:00:55.200000000, resyncing
0:00:00.163872738 16808 0x7f3058018e40 WARN                   pulse pulsesink.c:714:gst_pulsering_stream_overflow_cb:<pulsesink0> Got overflow

^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:21.427071810
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
`

**Comment by CartoonFan** [comment]
I see. I think I remember something similar happening to Clementine, Exaile, etc. I guess that means I'll have to go see if the gstreamer people know about it. Thanks for looking into it. Also, I hate to ask again, and I know it's not this bug, but is the FLAC decoder actually reading the Replay Gain reference level from files or is it hardcoded to 89 db? I ask because when using a value besides 89 db, it seems like the MP3 version of the song will play at a different volume compared to the FLAC version, even though both have the same reference level. I'm just wondering if that's the case so I can create another bug. Thanks again!
