### ISSUE TITLE
! Graphical bug issue: black bakground in tabs' and lyrics panel's background

### ISSUE THREAD

**Issue by geplus** [anonbeat/guayadeque#53]
Hi,
after the latest updates, guayadeque has this graphical issue in arch linux, related to #48

![prova111](https://user-images.githubusercontent.com/5302281/29243160-ca44577a-7f98-11e7-8cce-e507d7687893.png)

Can you fix this graphical problem for arch's users?

**Comment by n1trux** [comment]
The title and description are seriously lacking, geplus.

I have a similar issue in Fedora 26 with Guayadeque 0.4.5-35eaa95, see the attached screenshot. Both the tabs and the background of the lyrics are black, the background of the menu has a weird gradient behind it and if you change the layout everything is borked.

![bildschirmfoto_2017-09-03_13-04-29](https://user-images.githubusercontent.com/7255542/30002384-76250b3c-90a8-11e7-81d2-dee8f588c816.png)

[Log when starting from console](https://gist.github.com/n1trux/2bb2a69074cf6b5a4d69cefaa7c4751e) throws a lot of GTK errors.

**Comment by anonbeat** [comment]
Please can you check if with latest commit this problem is fixed. Also try to find places where this problem still happens. Thanks for your help

**Comment by anonbeat** [comment]
This have been confirmed to be fixed
