### ISSUE TITLE
Is guayadeque development on an indefinite hiatus / dead?

### ISSUE THREAD

**Issue by geplus** [anonbeat/guayadeque#54]
Hi
@anonbeat, is guayadeque's developement at a dead-point?

No update by you (not on github neither in the official forum) since August, major graphical issues without a response.
Can you post an official statement about guayadeque?

**Comment by anonbeat** [comment]
I am sorry but I have not much time lately and the little time I can find I use it on the qt port and in mastering technologies I need at work.

Of course any help is welcome

**Comment by geplus** [comment]
@anonbeat thak you for you timely answer.

I want to say you thank you for your hard work.
Guayadeque is an exellent music palyer, my favourite and one of the most complete in my opinion.
I hope I'll can test the qt version soon.The best thing is surely focus your energies on this port. Good luck for your projects.

**Comment by FSMaxB** [comment]
@anonbeat: Could you put the in-progress Qt port in a branch on GitHub?
