### ISSUE TITLE
Minor bug: guayadeque can't be selected in gnome-shell as default music player

### ISSUE THREAD

**Issue by studiosusmed** [anonbeat/guayadeque#56]
In Ubuntu 16.04 with guayadeque 0.4.5 installed, it is not possible to select guayadeque as the default music player in gnome-shell 3.20. 

After adding guayadeque.desktop to the mime file in /.local/share/applications. It shows up in the details dialogue. It would be nice to see the file changed by default during installation.

cheers and thx for this awesome player!

**Comment by anonbeat** [comment]
Guayadeque installer copy the guayadeque.desktop file to the /usr/share/applications folder. I think that is  enought
