### ISSUE TITLE
how to reset the playback counter

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#57]
Hi,

a user told me that the playback counter is already in the billions [1].
However, I would like to reset the playback counter, but I find no way for it.
With some music files I am already in the billions and the player counts ever further.
guayadeque version: 0.4.5-r2082.55efd99

[1] https://martinkg.fedorapeople.org/ErrorReports/guayadeque/Guayadeque%20Wiedergaben.png

**Comment by anonbeat** [comment]
This should be fixed with latest commit.
https://github.com/anonbeat/guayadeque/commit/77f28784ffafc719b21d9aa6e1409e561975c4d0
