### ISSUE TITLE
Another program instance is already running

### ISSUE THREAD

**Issue by Typhon7** [anonbeat/guayadeque#59]
First of all, thank you for the development of the player, I think it's the best music player on Linux and I've been using it a long time now. 

Since last commit, everytime I open a file when Guayadeque is already running I get the message "Another program instance is already running. Do you want to  continue with the program?". If I choose "No", the file is queued on the running instance, which is the desirable behaviour and the one I got before that commit. If I choose "Yes" a new instance is created, playing the file (but anyway the file is queued on the original instance). 

Is it possible for the dialog to not appear and to simply queue the file like it did before? Thank you.

**Comment by anonbeat** [comment]
ohh sorry. This was introduced by a recent change to allow ppl with defunt instances of guayadeque force starting the program...
Will try to find a solutions asap.

**Comment by anonbeat** [comment]
This should be fixed now! Thanks again for the bug report...

**Comment by Typhon7** [comment]
Fixed indeed. Thank you!
