### ISSUE TITLE
rpmlint reports: E: incorrect-locale-subdir /usr/share/locale/sr-latin/LC_MESSAGES

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#6]
guayadeque.x86_64: E: incorrect-locale-subdir /usr/share/locale/sr-latin/LC_MESSAGES/guayadeque.mo
guayadeque.x86_64: E: invalid-lc-messages-dir /usr/share/locale/sr-latin/LC_MESSAGES/guayadeque.mo
guayadeque-debuginfo.x86_64: I: checking
guayadeque-debuginfo.x86_64: I: checking-url http://guayadeque.org/ (timeout 10 seconds)
3 packages and 1 specfiles checked; 2 errors, 3 warnings.

should be /usr/share/locale/sr@latin/LC_MESSAGES/guayadeque.mo

**Comment by anonbeat** [comment]
Thanks for the bug report. This should be fixed now.

**Comment by martinkg** [comment]
Many thanks for the fix, its now ok.
