### ISSUE TITLE
upadte music folder = crash

### ISSUE THREAD

**Issue by ralpheeee88** [anonbeat/guayadeque#60]
I have update when opened to monitor my music folder. Every time i open guayadeque it scans the music folder and just when it is about to conclude the scan it force closes. If i can provide a log pls let me know. Thxs!

Just tried without the "update when opened" option and manually tried to do a scan / update and it continues to force close

deleted all guayadeque tmp folders ...still crashing
https://hastebin.com/ziresiketi.vbs

**Comment by ralpheeee88** [comment]
@anonbeat I removed the music folder did an update then added it back... No issues when starting up... If it crashes again after adding new music I will do the back trace.. Thxs for getting back:+1:

**Comment by anonbeat** [comment]
I close the issue then!!! Thanks for your support
