### ISSUE TITLE
Random ordering never visits some songs

### ISSUE THREAD

**Issue by robbat2** [anonbeat/guayadeque#63]
This is something I noticed by gut feel, and confirmed later.

I have ~130k songs in my collection, and some songs & albums are never being visited.

If I queue them manually, then they work fine (and last played is updated if possible [per issue #62]).

My lastfm data also shows that the distribution of plays is heavily concentrated in some songs/albums, and it's been a very long time since I heard others.

The Last Played column shows about 80% of my collection has not been played at all (I cleaned out my config and re-imported data not that long ago however).

**Comment by anonbeat** [comment]
Can you please tell me what you call 'random ordering' ?

**Comment by robbat2** [comment]
I have the following settings:
* Play random ALBUM when playlist is empty.
* 10 tracks left to start search
* 10 tracks added each time
* Don't repeat last 50 artists or last 200 tracks.

Of my ~130k songs, I have ~14k artists and ~18k albums.

**Comment by anonbeat** [comment]
Do you have smart play enabled? the bulb icon is shown ?

**Comment by robbat2** [comment]
Yes, smart mode is enabled.

**Comment by anonbeat** [comment]
Then disable it to use the random mode. It is selecting tracks from the current playing track and not randomly.

**Comment by robbat2** [comment]
Hmm, I had it enabled  because it only seems to strongly prefer single tracks if Smart is disabled. Maybe better documentation how how it considers them to be based?

**Comment by anonbeat** [comment]
Smart mode is based on playing tracks and search tracks that you should like based on last.fm service. If you start with the same track you will notice that not always pick the same tracks but with enough time it will select all the tracks that are related to each other.

Random mode is simply a random query to the database and it will pick a track or album depending on the setting you set.

You can limit the Smart mode and the Random mode with the Allow and Deny filters. You can make a filter that act like filters so you can select with tracks you can listen to even in random or smart mode. 

For example you can create a smart playlist with year > 79 and year < 90 to select only tracks from the 80s and select this playlist as allow. I usually set as deny filter the 'last played tracks' playlist.

Hope this helps

**Comment by robbat2** [comment]
Ok, so really this is intended behavior revealed by other weirdness:
* I do have add album set, but Random mode still adds only tracks sometimes. Possibly due to metadata inconsistency.
* Allow & Deny filter boxes are unusable with a collection this size. Every .m3u file seen has an entry in the filters.

**Comment by anonbeat** [comment]
If you dont want to create playlist for every .m3u uncheck 'Create playlists on scan' in the collections preferences.

**Comment by anonbeat** [comment]
Maybe that tracks are seen by guayadeque as entire albums as they have different album name or are in different folder.
