### ISSUE TITLE
Check for cover.jpg existence before access

### ISSUE THREAD

**Issue by robbat2** [anonbeat/guayadeque#64]
A directory does not have any write perms, there is a EPERM error raised if a file doesn't exist.
```
Error: can't open file '/home/mp3/from-susan-2/iTunes/cover.jpg' (error 13: Permission denied)
```

Would be better to check for the file and not print anything instead of spamming for every directory where this is the case.

**Comment by anonbeat** [comment]
The library update tries to extract the files if 'Scan embedded covers in audio files' is checked and no cover is found on that folder. In that case updates the database with the extracted file. In this situation my guess is that the extraction failed and the file is in the database as the album cover. 

I will try to fix that only update the database if the cover is really saved...
