### ISSUE TITLE
Turning the volume up after it has been at 0% for a while causes music playback problems

### ISSUE THREAD

**Issue by vedranMv** [anonbeat/guayadeque#65]
Hi, I've noticed some problems related to playback of streams (radio) and music files (.mp3) after the volume has been increased from 0% to some non-zero value.

1. After having the volume turned all the way down to 0% for about 5 sec. then bringing it back to e.g. 100% causes the music volume to stay low for some time before suddenly getting back to 100% (even though the control is set to 100% all the time)

2. If the volume stays at 0% for more than 10sec (10sec seems to be minimum for this) and then gets up to a non-zero value it will cause streams (such as radio) to reconnect/buffer; sometimes even causing playback problems after rebuffering period of few sec. 

3. Similarly, music files (such as .mp3) will experience interruption in playback after the player has been at 0% volume for more than 10 sec. Interruption lasts 1-2 sec and happens a couple of seconds after turning the volume up to a non-zero value.

I'm experiencing this in Ubutnu 16.04.3 LTS (edit: 64-bit version)

**Comment by anonbeat** [comment]
This should be solved now.
