### ISSUE TITLE
Gstreamer plugin missing

### ISSUE THREAD

**Issue by danxinnoble** [anonbeat/guayadeque#66]
Installed from git today (2017-11-27).

UI appears fine. When I try to play an mp3, I get the following error:
Error: Gstreamer error 'Your GStreamer installation is missing a plug-in."

Running on Ubuntu 16.01.

**Comment by anonbeat** [comment]
Try installing this plugins :
```
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
gstreamer1.0-plugins-ugly
gstreamer1.0-pulseaudio
```

**Comment by danxinnoble** [comment]
Yep. That worked. Thanks.
