### ISSUE TITLE
Unable to access context (right click) menu from File Browser

### ISSUE THREAD

**Issue by da2drae** [anonbeat/guayadeque#69]
Aim: to open tag editor to edit ID3 tags of a mp3 file.

Open Guayadeque.

Select: Sources -> check "File Browser"

Go to the file browser view

Browse to the appropriate folder, then right click an audio file.

Guayadeque freezes

Then the following error is generated:

_ASSERT INFO:_
_../src/gtk/clipbrd.cpp(737): assert "m_formatSupported" failed in GetData(): error retrieving data from_ _clipboard_

_BACKTRACE:_
_[1] wxClipboard::GetData(wxDataObject&)_
_[2] Guayadeque::guFilesListBox::CreateContextMenu(wxMenu*) const_
_[3] Guayadeque::guListView::OnContextMenu(wxContextMenuEvent&)_
_[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*,_ _wxEvent&)_
_[5] wxEvtHandler::SearchDynamicEventTable(wxEvent&)_
_[6] wxEvtHandler::TryHereOnly(wxEvent&)_
_[7] wxEvtHandler::ProcessEventLocally(wxEvent&)_
_[8] wxEvtHandler::ProcessEvent(wxEvent&)_
_[9] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)_
_[10] wxWindowBase::TryAfter(wxEvent&)_
_[11] wxVarScrollHelperEvtHandler::ProcessEvent(wxEvent&)_
_[12] wxEvtHandler::SafelyProcessEvent(wxEvent&)_
_[13] g_closure_invoke_
_[14] g_signal_emit_valist_
_[15] g_signal_emit_
_[16] gtk_propagate_event_
_[17] gtk_main_do_event_
_[18] g_main_context_dispatch_
_[19] g_main_loop_run_
_[20] gtk_main_
_[21] wxGUIEventLoop::DoRun()_
_[22] wxEventLoopBase::Run()_
_[23] wxAppConsoleBase::MainLoop()_
_[24] wxEntry(int&, wchar_t**)_
_[25] main_
_[26] __libc_start_main_
_[27] _start_

**You can then choose to continue or close the application but you are unable to edit the audio file.**

**Comment by anonbeat** [comment]
Cant reproduce it here...
