### ISSUE TITLE
Text Search boxes too small

### ISSUE THREAD

**Issue by spsf64** [anonbeat/guayadeque#73]
This is arch linux with cinnamon DE
It happens in "radio" and "my music"
See attached images, in both cases I just typed a letter "A" and I can only see some dots.

![screenshot from 2018-08-20 17-33-05](https://user-images.githubusercontent.com/1877391/44365200-7f761300-a49f-11e8-9307-54538bf9d661.png)

![screenshot from 2018-08-20 17-32-10](https://user-images.githubusercontent.com/1877391/44365201-800ea980-a49f-11e8-81a3-97281c4b1f87.png)

**Comment by anonbeat** [comment]
Can you compile it yourself or are you using it from repository? I need you to test a tiny patch to see if that helps. Can you do it ? if so email me to anonbeat @ gmail . com

**Comment by spsf64** [comment]
Sort of, I am not a programmer, lol! 
I forgot to say, using the git version from AUR: https://aur.archlinux.org/packages/guayadeque-git/
So, I believe any change you make in the code will be used when building the package...
Thanks for replying

**Comment by anonbeat** [comment]
Will need to install cinnamon then... Will let you know once I test the patch...
Thanks

**Comment by spsf64** [comment]
It happens with xfce too, just tested
In "My Music" tab I typed "iron"
This is the latest git I built yesterday.

![screenshot_2018-08-21_16-43-15](https://user-images.githubusercontent.com/1877391/44425190-8d8c6800-a561-11e8-931c-cb10b622e32f.png)

![screenshot_2018-08-21_16-42-59](https://user-images.githubusercontent.com/1877391/44425191-8d8c6800-a561-11e8-83f9-80886f29ba68.png)

**Comment by spsf64** [comment]
The problem is related to the theme I used, the pics posted above are with Adapta Theme
The adapta shows a bigger space however is the worst one to show any text;
Numix works partially; 

Arc theme is the only one working fine:
![arc-theme](https://user-images.githubusercontent.com/1877391/44430415-f7f8d480-a570-11e8-8518-50d70cf55665.png)

This is Adapta:
![adapta](https://user-images.githubusercontent.com/1877391/44430432-07781d80-a571-11e8-853a-09f9e66afb88.png)

This one is Numix:
![numix-theme](https://user-images.githubusercontent.com/1877391/44430441-11018580-a571-11e8-9fe5-71aebf5475ed.png)

**Comment by anonbeat** [comment]
Ahh ok thanks... will try to set those themes and see if the problem can be fixed.

**Comment by anonbeat** [comment]
Please can you check if something is better now ? I did a change in the latest commits to see if that solves the issue for you...

**Comment by spsf64** [comment]
Wow! It works perfectly now with adapta theme, thank you!!

**Comment by anonbeat** [comment]
Please can you confirm that the other inputs are correct too  ? thanks
