### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by GCamp6** [anonbeat/guayadeque#77]
If I follow the instruction in the README file for installation
```
./build 
sudo make install
```

in the terminal I get
```
CMake Error at CMakeLists.txt:38 (MESSAGE):
  wxWidgets not found!
-- Configuring incomplete, errors occurred!
```

and if I try with make I get
`make: ***  No rule to generate "install". Stopped`

I'm running LMDE 3

Is this the best way to install Guayadeque on a Debian based distro?

**Comment by anonbeat** [comment]
You need to install the dependencies...

Check if this instructions helps http://www.guayadeque.org/index.php?p=/discussion/1909/installation-18-04

**Comment by GCamp6** [comment]
Wow, that's quite some dependencies... I did non see that post thanks. Followed the instructions and I got it to work smoothly. Thanks a lot
