### ISSUE TITLE
Ability to temporarily disable a collection

### ISSUE THREAD

**Issue by robbat2** [anonbeat/guayadeque#79]
I have a collection stored on a NAS in the office, because it's too large for my laptop, but I want to have it available when I'm in the office.

I also have a smaller subset of it cloned for travel.

I'd like a way to disable any given collection because I know it's temporarily not available.

**Comment by sluedecke** [comment]
Probably a silly answer, but is hiding/showing the NAS based collection using:

Sources -> [Collection name] -> Show

useful for your usecase?

**Comment by robbat2** [comment]
Hiding the collection still leads to the player using it for the playlist smart populate.

**Comment by anonbeat** [comment]
Only the default collection is used to populate the playlist in smart mode.

**Comment by sluedecke** [comment]
Is "default" the first listed on Preferences -> Collections (which is an ordered list)?

**Comment by anonbeat** [comment]
Yes.. that is the default one
