### ISSUE TITLE
guayadeque source files without license header

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#8]
Can you please explain why those files ar with no license header ?

filelist:
https://bugzilla.redhat.com/attachment.cgi?id=1161083

**Comment by Strubbl** [comment]
just for further reference https://bugzilla.redhat.com/show_bug.cgi?id=1338140

**Comment by anonbeat** [comment]
Will fill the image files with gplv3 license. About the wxCurl ones will investigado the license as it is not my work. 
Will fix all the files soon.

Thanks for your help

**Comment by anonbeat** [comment]
The image files have been updated.

The wxCurl files have wxWidgets license.

**Comment by martinkg** [comment]
Sorry,
but why is wxCurl bundled and could you please try to unbundle it ? (like wxsqlite3)
wxcurl is as separate project available: https://sourceforge.net/projects/wxcurl/

**Comment by anonbeat** [comment]
Guayadeque include some patches that are not included in the project code. I sent them to the developer and was told there was going to be included but still waiting. Emailed again the developer about it...

**Comment by martinkg** [comment]
problem solved wxcurl was unbundled and replaced by libcurl.
