### ISSUE TITLE
reCAPTCHA V1 IS SHUTDOWN (not related to software!)

### ISSUE THREAD

**Issue by hubitor** [anonbeat/guayadeque#81]
Sorry I didn't know where else to report this.

I tried to register here:
[http://www.guayadeque.org/index.php?p=/entry/register](http://www.guayadeque.org/index.php?p=/entry/register)

but it seems that reCAPTCHA is not working.

**Comment by anonbeat** [comment]
I need to upgrade the whole guayadeque.org site... just need time to do it!

**Comment by anonbeat** [comment]
forums renewed...

**Comment by mirlace** [comment]
Thanks
