### ISSUE TITLE
MainFrame.cpp:3040: undefined reference to `wxAuiNotebook::GetPageIndex(wxWindow*) const'`

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#84]
Hi,
the compilation of the recent code fails on Fedora with this error message:

`guayadeque-dfc4acb6ad3c6211f0957a38c58c18d7a33290c9/src/ui/MainFrame.cpp:3040: undefined reference to `wxAuiNotebook::GetPageIndex(wxWindow*) const'`

the complete compilation log file can be found here:
https://kojipkgs.fedoraproject.org//work/tasks/4739/34124739/build.log

Thanks
Martin

**Comment by sluedecke** [comment]
Same happens to me ... I don't have a real fix, just a workaround to cmake missing the aui library.  To

`src/CMakeFiles/guayadeque.dir/link.txt `

I added

`-lwx_gtk3u_aui-3.0`

I use a local copy of the repository and build there manually.

**Comment by martinkg** [comment]
> Same happens to me ... I don't have a real fix, just a workaround to cmake missing the aui library. To
> 
> `src/CMakeFiles/guayadeque.dir/link.txt `
> 
> I added
> 
> `-lwx_gtk3u_aui-3.0`
> 
> I use a local copy of the repository and build there manually.

Thanks for your help, i solved it now by exporting LDFLAGS ...

```
export LDFLAGS="$LDFLAGS -lwx_gtk3u_aui-3.0"
%cmake . 
...
```

**Comment by Strubbl** [comment]
Thanks, package guayadeque-git for archlinux had the same issue, which is resolved by updated LDFLAGS.

**Comment by martinkg** [comment]
will fix it for the fedora package, with this flag:

`-DCMAKE_EXE_LINKER_FLAGS:STRING=-lwx_gtk3u_aui-3.0`
