### ISSUE TITLE
How about 0.4.6

### ISSUE THREAD

**Issue by sluedecke** [anonbeat/guayadeque#88]
It's been roughly 1.5 years and 82 commits since the last release.  How about tagging another version?

Guayadeque is still actively maintained so a new release would be a good sign :)

PS: any updates on the Qt port?  Or is it suspect to be [The Big Rewrite](http://chadfowler.com/2006/12/27/the-big-rewrite.html) (which I had suffered myself AT LEAST once)...

**Comment by anonbeat** [comment]
I agree that its about time to release 0.4.6. 

About Qt port my main problem is lack of time and also I underestimated the amount of time/work that needed.
