### ISSUE TITLE
 [abrt] guayadeque: wxFatalSignalHandler(int)(): guayadeque killed by SIGABRT

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#89]
Description of problem:
Open app.

Version-Release number of selected component:
guayadeque-0.4.6-1.fc30
Distribution: Fedora 30

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        guayadeque
crash_function: wxFatalSignalHandler(int)
executable:     /usr/bin/guayadeque
journald_cursor: s=a4981ef89cf74a2ebd2b14e3fd6223eb;i=1f088;b=fe765707f5a14e119716e6a814e7279d;m=1a02b5372;t=58b7f1ea36772;x=fcb0e663e832ac20
kernel:         5.1.8-300.fc30.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (1 frames)
 #2 wxFatalSignalHandler(int) at ../src/unix/utilsunx.cpp:1407

backtrace.txt and core_backtrace.txt are attached
[core_backtrace.txt](https://github.com/anonbeat/guayadeque/files/3302046/core_backtrace.txt)
[backtrace.txt](https://github.com/anonbeat/guayadeque/files/3302047/backtrace.txt)

[complete bugzilla report](https://bugzilla.redhat.com/show_bug.cgi?id=1721456)

**Comment by anonbeat** [comment]
I think this have been fixed. It was a bug in Preferences
