### ISSUE TITLE
Feature Request: Start with random song from main collection

### ISSUE THREAD

**Issue by sluedecke** [anonbeat/guayadeque#90]
Just an idea which I would love to have.  

User Story:
If I start guayadeque with an empty playlist and push PLAY, it asks me whether it shall play a random song from the main collection and to enable smart mode.  If yes, it selects song accordingly and starts playing (since I have smart play enabled, guayadeue keeps adding new songs to the playlist).

What do you think?

**Comment by sluedecke** [comment]
Dang ... already there ... cool stuff :)

**Comment by sluedecke** [comment]
Still ... only if guayadeque starts afresh, the player has no current track.  If the playlist is empty at this moment, it truly starts with a random song (if configured in prefs -> playback -> play random song|album if playlist is empty).

If the player control has a track, it does not select a random one.  I have to restart guayadeque to get an empty player control.

So I suggest this:  if one pushes stop while playback is already stopped, the player control shall be emptied.

**Comment by sluedecke** [comment]
Patch integrated with commit dbccd170d3ca1fea3686f2728b12a1c30a1849dd

**Comment by anonbeat** [comment]
Yes, you are right. I will fix this asap. Thanks

**Comment by sluedecke** [comment]
Great, thank you!
