### ISSUE TITLE
Aborted (core dumped) happens, when selecting View - Preferences - General

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#92]
Aborted (core dumped) happens, when selecting View - Preferences - General
Installed is the recent version from git 89c6ab233036f737ea2e9b7af820390e9bc10b66

**Comment by JohnyPeaN** [comment]
Had the same problem. After reverting commit [afafe04](https://github.com/anonbeat/guayadeque/commit/afafe0424c7fcc0dade7c680eefd82b263a402c4) it works again.

**Comment by anonbeat** [comment]
Got it... will fix it in a sec...

**Comment by JohnyPeaN** [comment]
Thanks, the crash is gone. Preferences>General dialog works.
