### ISSUE TITLE
Album shows wrong art when another album with the same name exists

### ISSUE THREAD

**Issue by arnova** [anonbeat/guayadeque#94]
I have several "Greatest Hits" albums from various artists. The problem is that Guayadeque seems to always show the art for the album of the first artist it can find. It seems like it only checks the album name but doesn't check the artist it belongs to.

**Comment by anonbeat** [comment]
Can you send me more details please ? where is shown ? what is yout collection structure ? can u post a capture ?

**Comment by arnova** [comment]
As it turns out the problem is a little different from what I initially thought. It turns out that some albums that don't have any album art set, use the art from the first (alphabetical) album in my collection, which happens to be "2Pac - Greatest Hits". My folder structure is like this:
- Artist1 - Album1\*.mp3|folder.jpg
- Artist1 - Album2\*.mp3|folder.jpg
- Artist2 - Album3\*.mp3|folder.jpg

And so on. So for the most part I use physical folder.jpg's for each album and not embedded art (for the most part).

If you need more info or help, let me know. I'm a Kodi-dev so I know my way around in C++ code (in Guayadeque I simply don't know where to look atm).

**Comment by arnova** [comment]
![image](https://user-images.githubusercontent.com/544531/81277612-ef05aa80-9054-11ea-96d8-db66adb02c42.png)

**Comment by anonbeat** [comment]
Can you contact me via email ? I cant reproduce the problem here
