### ISSUE TITLE
Smart play seems to only add songs from the same genre "type"

### ISSUE THREAD

**Issue by arnova** [anonbeat/guayadeque#95]
Being using to Kodi's "Partymode" for playing music, I expected Guayadeque's "Smart Play" to work in a similar way. But it seems that "Smart play" doesn't add random songs from your whole library but rather songs which have a "similar" genre type compared to the first song that was initially manually selected. For instance: When I manually play a song with genre "Rock", it will only add items which are also Rock in addition to "Alternative Rock" and "Grunge" but NOT eg. Metal, or "80's Pop". I've also tried a few other genres and there it seems to work the same way: When I manually select a song with genre "Metal", only new items with genre "Metal", "Speed Metal", "Thrash Metal" etc. are added.

It seems this is by design but I wasn't able to find any evidence to back this up. If it is by design: please add an option to disable it. If not: please fix ;-)

**Comment by anonbeat** [comment]
To do what you want disable smart mode and in Preferences -> Playback select Play random track/Album when playlist is empty

**Comment by arnova** [comment]
Yes but it would be great if you could simply have not just a single random track but a complete playlist with random tracks, like "Smart Play" does.

**Comment by arnova** [comment]
Hmm, it seems you're right after all. Somehow it didn't work before but now it does :-)
