### ISSUE TITLE
Tab contents stays visible after its closing

### ISSUE THREAD

**Issue by wojnilowicz** [anonbeat/guayadeque#97]
Steps to reproduce:
1) have "lyrics" and "last.fm" tabs available
2) switch to "last.fm" tab
3) close "last.fm" tab

Result:
Its content stays on "lyrics" tab. Look below for a demonstration
![before](https://user-images.githubusercontent.com/22069602/82137474-c893fc00-9818-11ea-9b7b-87fb5ebf36c4.png)
![after](https://user-images.githubusercontent.com/22069602/82137477-cb8eec80-9818-11ea-8a49-4831167a2501.png)

Expected result:
Content of "last.fm" tab should disappear.

Additional informations:
1) Guayadeque 0.4.6-42f77b6 from Fedora 32 on KDE

**Comment by anonbeat** [comment]
This have been fixed recently. Thanks
